apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-task5-config
data:
  AUTH_DATABASE_HOST: auth-postgres
  AUTH_DATABASE_USER: myuser
  AUTH_DATABASE_DB: myapp
  APP_URL: app-task5-service.auth.svc.cluster.local:9000
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-task5-secret
type: Opaque
data:
  AUTH_DATABASE_PASSWORD: cGFzc3dk
  AUTH_DATABASE_PASSWORD_WITH_NEW_LINE: cGFzc3dkCg==
